export const POST_TITLE_MIN_LENGTH = 1
export const POST_TITLE_MAX_LENGTH = 30

export const POST_CONTENT_MIN_LENGTH = 1
export const POST_CONTENT_MAX_LENGTH = 1000

export const POST_SHORT_DESCRIPTION_MIN_LENGTH = 1
export const POST_SHORT_DESCRIPTION_MAX_LENGTH = 100